GET https://csii203-at-num-2023autumn-w1.azurewebsites.net/api/endpoint2?code=vgtcas3Sthgog5Hq5ATf6mYfAZHumroe9KPFbeEXEFJ2AzFuaXvZhg==&studentid=21b1num2919

Content-Type: application/json

{
    "studentid": "21b1num2919",
    "food": "pizza",
    "type": "hot"
}




